### ISSUE TITLE
#6164 Static GIFs don't get displayed

### ISSUE THREAD

**Issue by ozramos** [ozramos/p5.js#1]
Related issue: https://github.com/processing/p5.js/issues/6164

# Tasks
- [x] Install p5.js locally
- [x] Fix main issue (can't load GIF with a single image)
- [x] Create inline doc examples with static and animated GIFs

### Notes
- Ask about adding instructions on how to get p5.js working locally for development purposes (for example, use `npm run docs:dev`)
- Ask if translations should be added to .gitignore
- Should we show a base64 demo?
- Do Animated PNGs work?

**Comment by ozramos** [comment]
![arnott-wallace-wink-single-frame](https://github.com/ozramos/p5.js/assets/69949201/ee0de518-ebed-4c31-a031-a1df96632528)

Added the following GIF example here: `\docs\reference\assets\arnott-wallace-wink-single-frame.gif`, which is just a single-frame extract from an already existing GIF in repo

**Comment by ozramos** [comment]
Replaced the following example

```js
function setup() {
  // here we use a callback to display the image after loading
  loadImage('assets/laDefense.jpg', img => {
    image(img, 0, 0);
  });
}
```

With the static image above. This is to reduce number of examples
